### ISSUE TITLE
use on('change') event vs. onChange callback

### ISSUE THREAD

**Issue by dhritzkiv** [AmpersandJS/ampersand-select-view#11]
I noticed that the view object has an onChange function, but not a event listener function.
Could this be added?

**Comment by cdaringe** [comment]
`onChange` is bound via a `change` event listener.  Please see [this line](https://github.com/AmpersandJS/ampersand-select-view/blob/master/ampersand-select-view.js#L123).  Thanks!

@bear, propose to close!

**Comment by kamilogorek** [comment]
Thanks for clarification @cdaringe.
