### ISSUE TITLE
ampersand-select-view does not extend ampersand-view

### ISSUE THREAD

**Issue by dhritzkiv** [AmpersandJS/ampersand-select-view#2]
Noticed that unlike ampersand-input-view, ampersand-select-view is not a descendant of ampersand-view, therefore not sharing many of the common methods (like extend).

Is this by design?

**Comment by e2jk** [comment]
Any progress on this issue? It would be great to be able to `.extend()` just like we do with `ampersand-input-view`.

**Comment by dhritzkiv** [comment]
@cdaringe was this meant to be closed? I don't believe 4.0.0 RC (PR #43) was merged with master yet.

**Comment by cdaringe** [comment]
@dhritzkiv we were going to add #45 to it, but just going to merge that separately before wraithgar pushes to npm.  i've just merged #43 it for now!  thanks man!  sorry for the inconvenience :)
