### ISSUE TITLE
inconsistent API within ampersand-*-view ecosystem

### ISSUE THREAD

**Issue by wraithgar** [AmpersandJS/ampersand-select-view#21]
To get the value from, say, `ampersand-input-view` you can get `.value` and expect the actual string value that would be sent when the form is submitted.  This is not the case with select-view.  This makes inspecting the entire form challenging, as it requires too much knowledge about the fields.

As part of trying to get ampersand-form-view a little easier to use, we should standardize the way these fields views work.  Namely, `getValue` and `setValue` should exist on them all and should accept and return actual string values that translate 1:1 to what will end up in the serialized form.

Right now, select-view is the closest to having this ready to go, as it currently has getOptionValue (which works exactly like getValue should) and a setValue (which works exactly as described above).

This preserves whatever under-the-hood .value or .currentValue or what have you that each fields view is doing separately.

So my proposal for this repo is to add a getValue() that either mirrors or forwards functionality to `getOptionValue`

**Comment by cdaringe** [comment]
hey @wraithgar, i think we may actually be set here.  it may not be as pretty as &-input-view, but `.value` functions as `getValue`, and `setValue` is dialed in.  additionally, we have formField view conventions running against it.

because of `yieldModel`,
>you can get .value and expect the actual string value that would be sent when the form is submitted

won't always hold true, but that's acceptable

OK to close it up?
