### ISSUE TITLE
Empty Options yields `invalid` Despite Being Set to required: false

### ISSUE THREAD

**Issue by cdaringe** [AmpersandJS/ampersand-select-view#22]
There's an open PR semi on this now: https://github.com/AmpersandJS/ampersand-select-view/pull/15
This bug is specific enough to be tracked in the issues section!

**Comment by cdaringe** [comment]
the problem with the SelectView is as follows. when the SelectView is initialized, this.value is set to null. If you provide a nully `value: xzy` to the constructor, then `.validate()` will never get called. The result is that when the form `checkValid()`, `.valid` is undefined on the SelectView, thus the form is invalid. Providing a null value is a realistic case. For example, I am querying for a value, and sometimes, that value doesn't exist. validate() won't be called because of this line in setValue(), triggered by the constructor, https://github.com/cdaringe/ampersand-select-view/blob/master/ampersand-select-view.js#L181 . I think the solution is perhaps to either:

1. set this.value to undefined, which could potentially still result in the same failiure mode
1. set an init flag or force flag to force setValue() down through .validate() no matter what at least once. In this regard the .valid property will always be set to a bool initially, vs now, where it can be undefined
1. eliminate the if (value === this.value) return; in setValue().  This is what i have done in my branch for the time being
InputView works a completely different way and has a different structure, otherwise I'd say let's just copy that over.

**Comment by wraithgar** [comment]
I think this one is very much related to https://github.com/AmpersandJS/ampersand-select-view/issues/23 and may even involve the same fix.
