### ISSUE TITLE
should not flag as invalid on initialization

### ISSUE THREAD

**Issue by wraithgar** [AmpersandJS/ampersand-select-view#23]
If I instantiate a new select-view with `required: true` and `unselectedText` defined, I get a `selection required` message when the form first loads.

**Comment by kamilogorek** [comment]
Let's get https://github.com/AmpersandJS/ampersand-select-view/pull/15 merged first and then we'll think about this one.

**Comment by erd0s** [comment]
It seems like this module is probably going to go towards extending an view but if anyone needs this functionality now I've done a hotfix over at https://github.com/erd0s/ampersand-select-view/tree/hotfix/delay-validation

**Comment by cdaringe** [comment]
[3.0.0](https://github.com/AmpersandJS/ampersand-select-view/commit/002201f5dc3a972fc25404a6d6a14675d1da9f6d) closed this issue
