### ISSUE TITLE
`GET` not working when `POST`/`PUT` was done with `yieldModel: false`

### ISSUE THREAD

**Issue by e2jk** [AmpersandJS/ampersand-select-view#27]
Situation: 2 models:

`group` which has:
```
    props: {
        id: 'any',
        abbreviation: ['string', true, ''],
        name: ['string', true, '']
    },
```

And `object` which has a `group` child (extract):

```
    var Group = require('./group');

    children: {
      relatedGroup: Group
    },
```

With the following form to edit the `object` (extract):

```
            var SelectView = require('ampersand-select-view');

            new SelectView({
                label: "Related Group",
                name: "relatedGroup",
                value: this.model && this.model.relatedGroup && this.model.relatedGroup.id,
                options: app.groups,
                required: false,
                idAttribute: 'id',
                textAttribute: 'fullName',
                yieldModel: false,
                parent: this
            })
```

Since `yieldModel` is set to False, only the Id of the child object is sent in the `POST`/`PUT` API call. That's fine.
When retrieving the object (either the single state or the collection), the fake API faithfully returns just the ID. I would think that's fine as well, since based on that ID we should be able to getOrFetch the state.

But with the following code in the view's initialize:

```
    initialize: function (spec) {
        var self = this;
        app.objects.getOrFetch(spec.id, {all: true}, function (err, model) {
            if (err) alert('couldnt find a model with id: ' + spec.id);
            self.model = model;
            console.log(self.model.relatedGroup);
            console.log(self.model.relatedGroup.id);
```
`self.model.relatedGroup` is an Object, with functionally empty: it has empty `abbreviation` and `name` string values, but `id` doesn't exist on the Object. Hence the call to `self.model.relatedGroup.id` returns `undefined`.
It looks like Ampersand.js tries to create the relatedGroup property on the `object` model, since `abbreviation` and `name` are present, but it somehow doens't understand the value it received from the server is just the ID.

Is there an equivalent to `yieldModel` but for the server > client direction? In other words, could the server just send the ID, and the client perform a `getOrFetch` on that collection with the ID returned?
Or does the server need to accept only the ID when `POST`/`PUT`, but send the full object when `GET`?

**Comment by e2jk** [comment]
At this moment I'm thinking about an alternative, not using the `children` but instead a `number` `props` that would contain the id of the `group`, and a `derived` property that would `getOrFetch` the `group` based on the id received from the API. Or is there a better way to handle this?

**Comment by cdaringe** [comment]
Hi @e2jk.  A couple of things:

1. `children` isn't *really* needed.  i'd put your data it in props as you've suggested
1. I understand that the intent of your question is how to get your API to return a result formatted a particular way, based on how you request it.  really, it's not related to `ampersand-select-view`, despite you asking if a server has similar functionality.  that's OK, but you'll probably want to dig through this issue in a forum more suited to API design.  however, keeping in helpful spirit, what the server does is entirely dependent on how the API you are using is designed *on the server*.  ampersand cannot control what the server gives back to the client--it can only SEND and RECEIVE, and hopefully whatever you have sent is reciprocated with something you want to receive!
1. if the object you got back is raw, make sure that you've defined a corresponding `state` or `model` definition for the `app.objects` collection.  I'd suppose this is a large source of your issue
1. additionally, check out https://github.com/ampersandjs/ampersand-state#parse to see how to mutate results from the server.

I think this issue can be closed :+1:   Good luck!

**Comment by kamilogorek** [comment]
Thanks @cdaringe, @e2jk let me know if you have any further questions.

**Comment by e2jk** [comment]
My question was more related to the Fake API. I would suppose that, since this is used for demo purposes, saving a model using `yieldModel` to the Fake API should have the Fake API return such a model.
Once the real API will be implemented, this is indeed another question.

**Comment by cdaringe** [comment]
Hey @e2jk, there are dozens of programs that fakeApi could be.  What it boils down to is that your API needs to be manually coded to support that feature.  Ampersand can't control your server.  Ampersand sync provides hooks to enable you to send all sorts of other data to the server which you could use to help facilitate this. But, the bottom line is that you can't blur these two subsystems together.  They are two components of one system, and they are generally entirely decoupled, meaning that one knows nothing about the other
