### ISSUE TITLE
reset() method for use with ampersand-form-view

### ISSUE THREAD

**Issue by dhritzkiv** [AmpersandJS/ampersand-select-view#30]
Feature request for a `reset` method to be called by `ampersand-form-view`

**Comment by wraithgar** [comment]
Reset now exists, thanks for your patience.

**Comment by nickryall** [comment]
Reset is not in yet. Pending on #32 which needs to be re-worked following #36

**Comment by cdaringe** [comment]
Hey nick, I added it, but later removed it so as to not conflict with your
PR.  Thanks for the catch.

On Saturday, March 28, 2015, Nick Ryall <notifications@github.com> wrote:

> Reset is not in yet. Pending on #32
> <https://github.com/AmpersandJS/ampersand-select-view/pull/32> which
> needs to be re-worked following #36
> <https://github.com/AmpersandJS/ampersand-select-view/pull/36>
>
> @cdaringe <https://github.com/cdaringe> Is this correct? I can't see reset
> in the latest source, but it is documented in the latest readme. Just
> checking is hasn't been left it out by accident before I re-submit a PR
> with it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AmpersandJS/ampersand-select-view/issues/30#issuecomment-87293531>
> .
>


-- 
Chris Dieringer
p: (503)358-8577
e: cdieringer@mrn.org
w: http://cdaringe.net/
