### ISSUE TITLE
SauceLabs tests won't run on Pull Requests

### ISSUE THREAD

**Issue by nickryall** [AmpersandJS/ampersand-select-view#35]
@bear @cdaringe

I 'think' the issue with Sauce Labs may be that because the travis.yml is using the secure access key, only users with write access to the repo will be able to have the tests run on forked PRs. 

In summary the solution is to either use the public keys in the travis.yml ( which would make the account prone to abuse  e.g. using it to run tests on other projects ) or using something like this:

https://github.com/twbs/savage

Related discussion can be found here:

https://support.saucelabs.com/entries/25614798-How-can-we-set-up-an-open-source-account-that-runs-tests-on-people-s-pull-requests-

**Comment by cdaringe** [comment]
interesting concept.  we could also just start merging into a `develop` branch vs master, and if the build fails, in develop, the maintainer could revert the merge commit?  that sure is undue overhead for the maintainer.  perhaps if we merged into a develop branch, then post--CI *tests-pass*, some hook could listen and merge that commit into master?  That's gotta be doable?  on *tests-fail* it should revert the commit too, that way multiple PRs hitting the develop branch at once wouldn't get merged into master together.

**Comment by nickryall** [comment]
Sounds good.  I think something that uses a mix of both of your suggestions could work.

i.e. If the tests fail the merge commit is automatically reverted and a message is posted back to the PR.  If the tests pass, the maintainer and contributors can then review the code and either manually merge into `master` or manually revert the merge commit and post a message to the PR.

**Comment by bear** [comment]
I added a Trello card for this - https://trello.com/c/jlx3EtvS

**Comment by nickryall** [comment]
Thanks @bear!

**Comment by cdaringe** [comment]
@bear, could we move forward with an inefficient solution until this gets resolved?  We've got a handful of helpful PRs idling.  I can live with a *no*, but here's a workaround proposal I think is reasonable:

* disable sauce testing temporarily
* add all major browsers, -ie, to testem.json
* dev runs `(git log -n 1 --pretty=format:"%H") > PR.txt; testem ci >> PR.txt;`
    * the above outputs the latest commit and results of all browser assertion results to a file.
    * dev uploads file to the PR.  alternatively, at least one reviewer checks out feature branch and runs xbrowser test suite and does a +1 +browser-test check off?
* reviewers assert that the latest commit on the PR matches the commit in the .txt, and that all assertions passed, and then the PR may be merged

Not wild about it, but it keeps us in motion

**Comment by bear** [comment]
@cdaringe lets' do that until I can get some consensus to the other solution.

I agree that moving forward with a workaround is better than no movement.

**Comment by wraithgar** [comment]
I'm all for the alternative that doesn't have us adding a `PR.txt` manually to each pr.  There's plenty of precedent in other projects where travis ci failed for some reason so the two +1's were from people running the tests locally. We just need to make sure we mention running the tests in our +1's. </2c>

**Comment by bear** [comment]
yea, if we have two people +1 in comments that tests are good that is all we need IMO

**Comment by cdaringe** [comment]
Excellent!  If someone can volunteer to update the ci process *not* to trigger sauce and also critique/bless https://github.com/AmpersandJS/ampersand-select-view/issues/38, we can be on our merry way!
