### ISSUE TITLE
How to implement multiselect in ampersand-select-view

### ISSUE THREAD

**Issue by Ratnesh-Github** [AmpersandJS/ampersand-select-view#37]
I am providing the multiple attribute in my template. So in browser, I am able to select multiple values. However, When I submit the form, the value which is given to the server is only the first one out of all those.  Is there a separate module for multiselect ?

**Comment by kamilogorek** [comment]
I'm pretty sure it's not supported atm, so it'd have to be added first.

**Comment by Ratnesh-Github** [comment]
Yes I think it is not supported right now. It is better to tag it as an enhancement request.

**Comment by kamilogorek** [comment]
Done. Cheers!

**Comment by bmulcahy** [comment]
I would also like to see this happen in the future something like what is implemented in this
http://davidstutz.github.io/bootstrap-multiselect/

**Comment by pgilad** [comment]
Hey @Ratnesh-Github - if adding a simple flag for specifying that this is a multi-select input is easy enough - you are welcome to add a PR

**Comment by cdaringe** [comment]
closing this issue for now.  ditto @pgilad--would love a :hammer:PR:hammer: for multi-select!  it's not on a roadmap/milestone at this point
