### ISSUE TITLE
Not compatible with ampersand-form-view@3.x

### ISSUE THREAD

**Issue by dhritzkiv** [AmpersandJS/ampersand-select-view#42]
Since upgrading to `v3.x` of `ampersand-form-view`, `ampersand-select-view` hasn't been rendering (either `v2.x` or `v3.x`)

[Here's a demo of it not working.](http://requirebin.com/?gist=f5d09550c1aaf6d89c63)

[Here's the same code – now working–, but with ampersand-form-view@2.x](http://requirebin.com/?gist=4a343694a1772363a4de)

**Comment by cdaringe** [comment]
@dhritzkiv,

- here's the issue, detailed: https://github.com/AmpersandJS/ampersand-form-view/issues/41 
- here it is, summarized:
    - SelectView `render()`s immediately on construction, which is not expected view behavior on construction.  it immediately sets `.rendered` to true
    - FormView doesn't call `render()` on fieldViews if they are *already rendered*.

I just patched up &-checkbox-view to [not `render()` during construction](https://github.com/AmpersandJS/ampersand-checkbox-view/pull/7), but it needs core_team and community review.  select-view will be soon.
