### ISSUE TITLE
Validation error message not showing on parent form submit

### ISSUE THREAD

**Issue by ErikWittern** [AmpersandJS/ampersand-select-view#47]
I am using an ampersand-select-view within an ampersand-form-view like this:
```javascript
new FormView({
  ...
  fields: [
    ...
    new SelectView({
      el: self.queryByHook('category'),
      name: 'category',
      options: categoryOptions,
      label: 'Main Category *',
      required: true,
      requiredMessage: "Please select a category."
    })
  ]
});
```
The select-view renders correctly. It is also considered in the form view's validation - selecting no option does prevent the submit. However, the error message is not displayed upon submit. The error is shown, though, if I select an entry and then deselect it again. 

I use other ampersand-input-views in the same FormView, which work fine.

**Comment by cdaringe** [comment]
hello, can you provide more input?  are you by chance also using `unselectedText`?  is there a falsy first value other than 0 for your top option?  i tested this and saw the desired behavior.  a requirebin would be helpful!

**Comment by ErikWittern** [comment]
Hi Christopher, thanks for the reply! I tried to reproduce the error here: http://requirebin.com/?gist=ad163481d1910b99ed48. Interestingly, the message-container seems to get displayed after validation, but the message-text is not shown. Maybe I am just doing something stupid in consuming the view / setting up the form view?

**Comment by cdaringe** [comment]
@ErikWittern, awesome.  thanks man!  so there are two issues.
- adding the empty string `''` tells the select that `''` is a **valid** option.  please use `unselectedText`.
- there's a little bug where setting `''` as `unselectedText` isn't honored.  i'm pushing a bugfix for review now.  i ran a little demo and it seems to be working fine

**Comment by ErikWittern** [comment]
Fantastic, thank you very much, Christopher!

**Comment by ErikWittern** [comment]
The update to v4.0.0 fixed my issue.
