### ISSUE TITLE
Need an option to set unselectedText to be an disabled option

### ISSUE THREAD

**Issue by joy01804** [AmpersandJS/ampersand-select-view#49]
Currently the placeholder text is select-able.  I think it makes a lot of sense if you can't select the placeholder.

Or can you make this module extendable, so I can customize renderOptions function.

**Comment by cdaringe** [comment]
hi @joy01804.  only in cases where the field is required should such a rule apply.  additionally, this makes assumptions about the greater form behavior.  for instance, a combination of other field values may programmatically force the control to one value or another, including the placeholder (`''`) option.  This module does extend AmpersandView, which should have '.extend' on the prototype.  Extend at your leisure :smile: .  Let me know your thoughts.  Thanks!

**Comment by joy01804** [comment]
ETA on when the version with ampersand-view will be release tagged?
v3.0.1 does not have ampersand-view yet.

**Comment by cdaringe** [comment]
yea, looks like 4.0.0 didn't get shipped. @wraithgar is the man for that

**Comment by wraithgar** [comment]
Oh dangit I am so sorry.  Shipping `v4.0.0` now
