### ISSUE TITLE
Ability to use the <optgroup> element

### ISSUE THREAD

**Issue by e2jk** [AmpersandJS/ampersand-select-view#61]
It would be great to be able to pass to `options` something along the lines of:
```
[ {"Options 1": ["Option 1.1", "Option 1.2"] }, {"Options 2": ["Option 2.1", "Option 2.2"] } ]
```
and get something like this as the generated `<select>`:
```
<select>
  <optgroup label="Options 1">
     <option>Option 1.1</option>
     <option>Option 1.2</option>
  </optgroup>
  <optgroup label="Options 2">
     <option>Option 2.1</option>
     <option>Option 2.2</option>
  </optgroup>
</select>
```
Example: http://jsfiddle.net/JaZAm/1/

**Comment by cdaringe** [comment]
i agree, that would be rad!  i'm not actively enhancing select-view ATM, more just working to keep it afloat, but that may change soon.  i'd definitely give such a PR serious consideration if someone wants to take a stab at it.  hopefully it wouldn't be too much work

**Comment by e2jk** [comment]
Pull request created (I need some help creating tests): #65
