### ISSUE TITLE
Update ampersand-view dependency

### ISSUE THREAD

**Issue by achingbrain** [AmpersandJS/ampersand-select-view#71]
Versions of ampersand-view before 9.0.2 depend on get-object-path@0.0.2 - this has just been [removed from npm](https://github.com/azer/get-object-path/issues/1).

Any chance of this module updating it's ampersand-view dep?

**Comment by wraithgar** [comment]
Yes, a PR updating that dependency would most likely be quickly accepted.

**Comment by achingbrain** [comment]
Do you know what the breaking changes are between 8 and 9?

**Comment by wraithgar** [comment]
Yep! There were two small breaking changes in some defaults, outlined here: https://github.com/AmpersandJS/ampersand-view#changelog

I don't think those specifically affect this module, but because this is returning an ampersand-view a PR bumping 8 to 9 would constitute a major bump in this module.

**Comment by imorrison** [comment]
Okay, I just started opening up a couple PRs to help resolve this. I can't update the ampersand-form-view until the input and checkbox views are also updated :neutral_face:

**Comment by imorrison** [comment]
Something is wrong with the travis-ci config:

> Zuul tried to run tests in saucelabs, however no saucelabs credentials were provided.

This appears in all of my PRs.

**Comment by wraithgar** [comment]
Sorry about that, external PRs fail cause of the way travis-ci handles encrypted vars.

**Comment by achingbrain** [comment]
Looks like timezones got the better of me and this has been done.  Thanks!

**Comment by wraithgar** [comment]
Thanks for all your effort on these PRs @achingbrain

**Comment by imorrison** [comment]
Perfect, here is the final one: https://github.com/AmpersandJS/ampersand-form-view/pull/62

**Comment by achingbrain** [comment]
I think @imorrison has been doing all the work :wink:
